### ISSUE TITLE
New Game button not working. 

### ISSUE THREAD

**Issue by pozgo** [TitanKaempfer/Mad-Games-Tycoon-Real-Life-Mod#19]
After adding the mod it's impossible to either start new game or sandbox. Only loading save works which is not great since no mods are active on old gameplay. 

Any idea what might be the cause of this?

**Comment by TitanKaempfer** [comment]
I'm sorry for the late reply, I wasn't really active anymore for private reasons and put this project mostly aside.

In how far is it no longer possible to create a new game for you? Is there an error message or is the button just unclickable or have you perhaps installed other mods as well or edited some yourself? The latter one could potentially cause compability issues.
If you tried using special settings or anything, let me know. 

Every piece of information can help finding the cause of the problem, because I can't seem to recreate this issue.


PS: I'm about to release a newer version of this mod (1.3.10) and tested it right now, so if the issue was created with any more recent update, it should be gone. If it persists, let me know and I can try look into it more.
